In [1]:
from open_dataset_store import quick_start
store = quick_start('.', backend='local')

Store initialised at: . (Backend: local)

In [10]:
sum = store.summary()

📊 Dataset Store Summary
==============================
Base Directory : .
Backend        : local
------------------------------
Entities (Total: 2)
  - zones: 2
------------------------------
Entries (Total: 2)
  - experiments: 2
==============================

In [11]:
store.list_entries('experiments')

,entry_id,entity_id,timestamp,description,raw_csv_path,processed_files
0,entry_0001,zone_001,1783344483,Senosr Data Test,raw_data/experiments/entry_0001_zone_001_17833...,{}
1,entry_0002,zone_001,1783344565,"Test CO2 variation, single person come in and ...",raw_data/experiments/entry_0002_zone_001_17833...,{}

In [21]:
df_1 = store.get_entry_raw_data('experiments','entry_0001')
sum= store.get_df_summary(df_1, detailed=True)

--- Data Summary (Detailed) ---

,Column Name,Data Type,Total Records,Missing Values,Min,Max,Mean,Std Dev,Unique Values,Most Frequent
0,timestamp,object,239,0,NaN,NaN,NaN,NaN,239.0,2026-07-02T10:31:07.440Z
1,outside_t,float64,239,0,28.377,32.044,31.596586,0.621942,NaN,NaN
2,outside_h,float64,239,0,63.219,76.107,65.332138,2.179146,NaN,NaN
3,outside_c,int64,239,0,405.000,516.000,467.255230,26.106877,NaN,NaN
4,outside_p,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
5,outside_a,int64,239,0,1.000,2.000,1.280335,0.450105,NaN,NaN
6,outside_v,int64,239,0,26.000,81.000,55.460251,12.979197,NaN,NaN
7,room1_sensor1_t,float64,239,0,27.801,28.260,27.995925,0.079778,NaN,NaN
8,room1_sensor1_h,float64,239,0,67.990,69.643,68.851623,0.324312,NaN,NaN
9,room1_sensor1_c,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
10,room1_sensor1_p,float64,239,0,952.310,952.718,952.466444,0.077371,NaN,NaN
11,room1_sensor1_a,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
12,room1_sensor1_v,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
13,room1_sensor2_t,float64,239,0,28.276,31.645,31.130356,0.560216,NaN,NaN
14,room1_sensor2_h,float64,239,0,68.116,79.931,70.397029,2.030544,NaN,NaN
15,room1_sensor2_c,int64,239,0,400.000,539.000,480.648536,29.983783,NaN,NaN
16,room1_sensor2_p,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
17,room1_sensor2_a,int64,239,0,1.000,2.000,1.447699,0.498301,NaN,NaN
18,room1_sensor2_v,int64,239,0,20.000,94.000,62.347280,15.339598,NaN,NaN
19,supply_t,float64,239,0,29.756,30.830,30.481925,0.123452,NaN,NaN
20,supply_h,float64,239,0,67.675,75.034,69.782439,0.846456,NaN,NaN
21,supply_c,int64,239,0,400.000,505.000,421.556485,18.428717,NaN,NaN
22,supply_p,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
23,supply_a,int64,239,0,1.000,2.000,1.008368,0.091285,NaN,NaN
24,supply_v,int64,239,0,12.000,75.000,32.380753,10.047858,NaN,NaN
25,return_t,float64,239,0,28.966,32.454,31.924556,0.484675,NaN,NaN
26,return_h,float64,239,0,63.275,75.128,65.053866,1.825031,NaN,NaN
27,return_c,int64,239,0,400.000,587.000,448.958159,33.086313,NaN,NaN
28,return_p,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
29,return_a,int64,239,0,1.000,2.000,1.079498,0.271082,NaN,NaN
30,return_v,int64,239,0,10.000,124.000,46.384937,17.176125,NaN,NaN
31,mixed_t,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
32,mixed_h,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
33,mixed_c,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
34,mixed_p,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
35,mixed_a,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
36,mixed_v,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
37,cooler_t,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
38,cooler_h,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
39,cooler_c,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
40,cooler_p,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
41,cooler_a,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
42,cooler_v,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
43,heated_t,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
44,heated_h,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
45,heated_c,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
46,heated_p,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
47,heated_a,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
48,heated_v,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
49,mixer,int64,239,0,0.000,42.000,41.121339,6.023582,NaN,NaN
50,fan,int64,239,0,0.000,50.000,48.953975,7.170930,NaN,NaN
51,flowrate,int64,239,0,2071.000,2288.000,2137.129707,26.312040,NaN,NaN
52,coolerState,int64,239,0,0.000,1.000,0.974895,0.156771,NaN,NaN
53,heaterState,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN
54,humidifierState,int64,239,0,0.000,0.000,0.000000,0.000000,NaN,NaN