In [21]:
from open_dataset_store import quick_start
import pandas as pd
import numpy as np

In [22]:
store = quick_start('.', backend='local')
sum = store.summary()

Store initialised at: . (Backend: local)
📊 Dataset Store Summary
==============================
Base Directory : .
Backend        : local
------------------------------
Entities (Total: 2)
  - zones: 2
------------------------------
Entries (Total: 2)
  - experiments: 2
==============================

In [23]:
store.list_entries('experiments')

,entry_id,entity_id,timestamp,description,raw_csv_path,processed_files,processed_metadata
0,entry_0001,zone_001,1783344483,Senosr Data Test,raw_data/experiments/entry_0001_zone_001_17833...,{'refactored_data': 'processed_data/experiment...,{'refactored_data': {}}
1,entry_0002,zone_001,1783344565,"Test CO2 variation, single person come in and ...",raw_data/experiments/entry_0002_zone_001_17833...,{'refactored_data': 'processed_data/experiment...,{'refactored_data': {}}

In [24]:
df_1 = store.get_entry_raw_data('experiments','entry_0002')
sum= store.get_df_summary(df_1, detailed=True)

--- Data Summary (Detailed) ---

,Column Name,Data Type,Total Records,Missing Values,Min,Max,Mean,Std Dev,Unique Values,Most Frequent
0,timestamp,str,1004,0,NaN,NaN,NaN,NaN,1004.0,2026-07-02T11:41:35.155Z
1,outside_t,float64,1004,0,30.453,31.649,31.106389,0.225479,NaN,NaN
2,outside_h,float64,1004,0,63.284,69.455,66.482361,1.461979,NaN,NaN
3,outside_c,int64,1004,0,400.000,814.000,522.074701,101.141192,NaN,NaN
4,outside_p,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
5,outside_a,int64,1004,0,1.000,3.000,1.571713,0.554000,NaN,NaN
6,outside_v,int64,1004,0,15.000,339.000,90.494024,61.449547,NaN,NaN
7,room1_sensor1_t,float64,1004,0,27.150,27.745,27.408180,0.140028,NaN,NaN
8,room1_sensor1_h,float64,1004,0,67.774,73.621,71.333141,1.719937,NaN,NaN
9,room1_sensor1_c,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
10,room1_sensor1_p,float64,1004,0,952.769,955.170,953.909909,0.730123,NaN,NaN
11,room1_sensor1_a,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
12,room1_sensor1_v,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
13,room1_sensor2_t,float64,1004,0,30.080,31.242,30.724208,0.242060,NaN,NaN
14,room1_sensor2_h,float64,1004,0,68.421,74.398,71.575820,1.527962,NaN,NaN
15,room1_sensor2_c,int64,1004,0,403.000,864.000,602.952191,150.647137,NaN,NaN
16,room1_sensor2_p,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
17,room1_sensor2_a,int64,1004,0,1.000,3.000,1.839641,0.824102,NaN,NaN
18,room1_sensor2_v,int64,1004,0,25.000,494.000,154.239044,111.329895,NaN,NaN
19,supply_t,float64,1004,0,29.592,30.894,30.266215,0.280316,NaN,NaN
20,supply_h,float64,1004,0,66.834,73.826,70.792679,1.528579,NaN,NaN
21,supply_c,int64,1004,0,400.000,2382.000,578.071713,163.668801,NaN,NaN
22,supply_p,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
23,supply_a,int64,1004,0,1.000,5.000,1.775896,0.792900,NaN,NaN
24,supply_v,int64,1004,0,16.000,6931.000,151.325697,256.544389,NaN,NaN
25,return_t,float64,1004,0,31.086,32.076,31.706318,0.212754,NaN,NaN
26,return_h,float64,1004,0,63.090,68.880,65.675913,1.264672,NaN,NaN
27,return_c,int64,1004,0,400.000,956.000,603.198207,147.183595,NaN,NaN
28,return_p,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
29,return_a,int64,1004,0,1.000,4.000,1.838645,0.814782,NaN,NaN
30,return_v,int64,1004,0,16.000,821.000,153.180279,111.206097,NaN,NaN
31,mixed_t,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
32,mixed_h,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
33,mixed_c,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
34,mixed_p,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
35,mixed_a,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
36,mixed_v,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
37,cooler_t,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
38,cooler_h,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
39,cooler_c,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
40,cooler_p,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
41,cooler_a,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
42,cooler_v,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
43,heated_t,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
44,heated_h,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
45,heated_c,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
46,heated_p,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
47,heated_a,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
48,heated_v,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
49,mixer,int64,1004,0,48.000,48.000,48.000000,0.000000,NaN,NaN
50,fan,int64,1004,0,60.000,60.000,60.000000,0.000000,NaN,NaN
51,flowrate,int64,1004,0,2022.000,2277.000,2156.112550,48.053230,NaN,NaN
52,coolerState,int64,1004,0,1.000,1.000,1.000000,0.000000,NaN,NaN
53,heaterState,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN
54,humidifierState,int64,1004,0,0.000,0.000,0.000000,0.000000,NaN,NaN

In [25]:
store.summary_plot(
    df_1,
    columns=['room1_sensor2_t','room1_sensor2_h','room1_sensor1_t','room1_sensor1_h','room1_sensor2_c'],
    separate_plots=True
    
    )

In [14]:
from plotly.io import renderers
import plotly.express as px

fig = px.line(
    data_frame=df_1,
    # x='timestamp',
    y='room1_sensor2_c',
    
    
)

fig.show(renderers='vscode')

In [26]:
# outdoor_c =400
# outdoor_t =room1_sensor2_t
# outdoor_h =room1_sensor2_h
# indoor_t = room1_sensor1_t
# indoor_h = room1_sensor1_h
# indoor_c = room1_sensor2_c
# n_occ = 1->[1:100], 0->[101:205], 1->[205: rest]

df = df_1
new_df = pd.DataFrame()
new_df['indoor_t'] = df['room1_sensor1_t']
new_df['indoor_h'] = df['room1_sensor1_h']
new_df['indoor_c'] = df['room1_sensor2_c']
new_df['outdoor_t'] = df['room1_sensor1_t']
new_df['outdoor_h'] = df['room1_sensor1_h']
new_df['outdoor_c'] = 400
new_df['n_occ'] = 1
new_df.iloc[0:420, new_df.columns.get_loc('n_occ')] = 0
new_df.iloc[600:780, new_df.columns.get_loc('n_occ')] = 2

In [27]:
store.summary_plot(
    new_df,
    columns=['indoor_t','indoor_h','indoor_c','outdoor_t','outdoor_h','outdoor_c','n_occ'],
    separate_plots=True
)

In [28]:
store.add_processed_data(
    entry_type="experiments",
    entry_id="entry_0002",
    tag="refactored_data",
    df=new_df
)

✅ Processed data 'refactored_data' saved and linked to entry 'entry_0002'.

'refactored_data'

In [29]:
df_red = store.get_entry_processed_data('experiments','entry_0002','refactored_data')

In [30]:
store.summary_plot(
    df_red,
    columns=['indoor_t','indoor_h','indoor_c','outdoor_t','outdoor_h','outdoor_c','n_occ'],
    separate_plots=True
)

In [20]:
sum = store.get_df_summary(df_red)

--- Data Summary  ---

  Column Name Data Type  Total Records  Missing Values
0    indoor_t   float64           1004               0
1    indoor_h   float64           1004               0
2    indoor_c     int64           1004               0
3   outdoor_t   float64           1004               0
4   outdoor_h   float64           1004               0
5   outdoor_c     int64           1004               0
6       n_occ     int64           1004               0