In [1]:
from open_dataset_store import quick_start
import pandas as pd
import numpy as np

In [3]:
store = quick_start('.', backend='local')
sum = store.summary()

Store initialised at: . (Backend: local)
📊 Dataset Store Summary
==============================
Base Directory : .
Backend        : local
------------------------------
Entities (Total: 2)
  - zones: 2
------------------------------
Entries (Total: 2)
  - experiments: 2
==============================

In [11]:
store.list_entries('experiments')

,entry_id,entity_id,timestamp,description,raw_csv_path,processed_files,processed_metadata
0,entry_0001,zone_001,1783344483,Senosr Data Test,raw_data/experiments/entry_0001_zone_001_17833...,{'refactored_data': 'processed_data/experiment...,{'refactored_data': {}}
1,entry_0002,zone_001,1783344565,"Test CO2 variation, single person come in and ...",raw_data/experiments/entry_0002_zone_001_17833...,{'refactored_data': 'processed_data/experiment...,{'refactored_data': {}}
2,entry_0003,zone_002,1785480438,Test 1,raw_data/experiments/entry_0003_zone_002_17854...,{},NaN
3,entry_0004,zone_002,1785480903,Test 2,raw_data/experiments/entry_0004_zone_002_17854...,{},NaN

In [9]:
csv_path = "./Day 4 Test 2_2026-07-31.csv"
df = pd.read_csv(csv_path)
df.head()

,timestamp,outside_t,outside_h,outside_c,outside_p,outside_a,outside_v,room_1_t,room_1_h,room_1_c,...,heated_c,heated_p,heated_a,heated_v,mixer,fan,flowrate,coolerState,heaterState,humidifierState
0,2026-07-31T03:55:17.380Z,29.6,72.7,416,0,1,31,23.7,55.4,0,...,0,0,0,0,100,50,0,0,0,0
1,2026-07-31T03:55:22.379Z,29.6,72.6,405,0,1,26,23.7,55.4,0,...,0,0,0,0,100,50,0,0,0,0
2,2026-07-31T03:55:27.379Z,29.6,72.2,400,0,1,16,23.7,55.4,0,...,0,0,0,0,100,50,0,0,0,0
3,2026-07-31T03:55:32.379Z,29.5,71.7,400,0,1,18,23.7,55.4,0,...,0,0,0,0,100,50,0,0,0,0
4,2026-07-31T03:55:37.380Z,29.6,71.0,400,0,1,19,23.7,55.4,0,...,0,0,0,0,100,50,0,0,0,0

In [10]:
entry_id = store.create_entry_from_df(
    entry_type="experiments",
    df=df,
    entity_id="zone_002",
    description="Test 2",
)

✅ Entry 'entry_0004' created. File saved as entry_0004_zone_002_1785480903_data.csv